apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd  # MANDATORY
spec:
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.jetstack.io/'
    targetRevision: v1.6.1
    chart: cert-manager
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true