apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd  # MANDATORY
spec:
  destination:
    name: ''
    namespace: external-dns
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 5.5.0
    chart: external-dns
    helm:
      values: |
        dryRun: false

        aws:
          region: "ap-south-1"

        rbac:
          create: true

        policy: "sync"

        domainFilters:
          - dh4r4pvj.ga

        # set via helm so that you can refer to role ARN from terraform
        podAnnotations:
          iam.amazonaws.com/role: "external-dns-role"

        resources:
          limits:
            cpu: 5m
            memory: 50Mi
          requests:
            cpu: 3m
            memory: 50Mi

        metrics:
          enabled: true
          serviceMonitor:
            enabled: false
            selector:
              release: kube-prometheus-stack