apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hpa-operator
  namespace: argocd  # MANDATORY
spec:
  destination:
    namespace: hpa-operator
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://kubernetes-charts.banzaicloud.com'
    targetRevision: 0.4.0
    chart: hpa-operator
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true