apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube2iam
  namespace: argocd  # MANDATORY
spec:
  destination:
    name: ''
    namespace: kube2iam
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    path: ''
    repoURL: 'https://jtblin.github.io/kube2iam/'
    targetRevision: 2.6.0
    chart: kube2iam
    helm:
      values: |
        host:
          # docker0 is used
          iptables: true
          # flannel
          #interface: cni0
          # Calico
          interface: cali+
        rbac:
          create: true
        extraArgs:
          auto-discover-base-arn: 
          auto-discover-default-role: true
        verbose: false
        resources:
          limits:
            cpu: 4m
            memory: 16Mi
          requests:
            cpu: 4m
            memory: 16Mi
        prometheus:
          service:
            enabled: true
          serviceMonitor:
            enabled: true
            labels:
              release: kube-prometheus-stack

