apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd  # MANDATORY
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 20.0.1
    chart: kube-prometheus-stack
    helm:
      values: |
        kubeScheduler:
          enabled: false
        kubeControllerManager:
          enabled: false
        grafana:
          ingress:
            enabled: true
            hosts:
            - grafana.dh4r4pvj.ga
            tls:
            - secretName: grafana-general-tls
              hosts:
              - grafana.dh4r4pvj.ga
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              kubernetes.io/ingress.class: nginx
          additionalDataSources:
          - name: Loki
            type: loki
            url: http://loki:3100
            access: proxy
            orgId: 1
            version: 1
        prometheus:
          ingress:
            enabled: true
            hosts:
            - prometheus.dh4r4pvj.ga
            tls:
            - secretName: prometheus-general-tls
              hosts:
              - prometheus.dh4r4pvj.ga
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              kubernetes.io/ingress.class: nginx
            paths:
            - /
            pathType: ImplementationSpecific
        alertmanager:
          config:
            global:
              resolve_timeout: 5m
              slack_api_url: 'https://hooks.slack.com/services/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'
            route:
              group_by: ['job']
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 12h
              receiver: 'slack-notifications'
              routes:
              - match:
                  alertname: Watchdog
                receiver: 'null'
            receivers:
            - name: 'null'
            - name: 'slack-notifications'
              slack_configs:
              - channel: '#k8s-alerts'
                send_resolved: true
                icon_url: https://avatars3.githubusercontent.com/u/3380462
                title: |-
                  [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
                  {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
                    {{" "}}(
                    {{- with .CommonLabels.Remove .GroupLabels.Names }}
                      {{- range $index, $label := .SortedPairs -}}
                        {{ if $index }}, {{ end }}
                        {{- $label.Name }}="{{ $label.Value -}}"
                      {{- end }}
                    {{- end -}}
                    )
                  {{- end }}
                text: >-
                  {{ range .Alerts -}}
                  *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

                  *Description:* {{ .Annotations.description }}

                  *Details:*
                    {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                    {{ end }}
                  {{ end }}
            templates:
            - '/etc/alertmanager/config/*.tmpl'

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd  # MANDATORY
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    path: ''
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 2.8.1
    chart: loki

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd  # MANDATORY
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    path: ''
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 3.9.1
    chart: promtail
    helm:
      values: |
        config:
          lokiAddress: http://loki:3100/loki/api/v1/push
          snippets:
            extraScrapeConfigs: |
              - job_name: kubelet-journal-logs
                journal:
                  max_age: 12h
                  labels:
                    job: systemd-journal
                pipeline_stages:
                - match:
                    selector: '{unit!="kubelet.service"}'
                    action: drop
                relabel_configs:
                  - source_labels: ['__journal__systemd_unit']
                    target_label: 'unit'
                  - source_labels: ['__journal__hostname']
                    target_label: 'hostname'
              - job_name: kubernetes-events
                kubernetes_sd_configs:
                - role: pod
                pipeline_stages:
                - match:
                    selector: '{app="eventrouter"}'
                    stages:
                    - json:
                        expressions:
                          namespace: event.metadata.namespace
                    - labels:
                        namespace: ""
