apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
  namespace: argocd  # MANDATORY
spec:
  destination:
    name: ''
    namespace: storage
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    path: ''
    repoURL: 'https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/'
    targetRevision: 4.0.10
    chart: nfs-subdir-external-provisioner
    helm:
      values: |
        nfs:
          server:
            fs-0e7afb76f7f065ba5.efs.ap-south-1.amazonaws.com
          path: "/"
        storageClass:
          name: "efs-client"
        resources:
          limits:
            cpu: 20m
            memory: 50Mi
          requests:
            cpu: 5m
            memory: 50Mi
