apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: kube-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ required "Please provide AWS_ACCESS_KEY_ID" .Values.s3Credentials.AWS_ACCESS_KEY_ID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ required "Please provide AWS_SECRET_ACCESS_KEY" .Values.s3Credentials.AWS_SECRET_ACCESS_KEY | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: restic-config
  namespace: kube-system
type: Opaque
data:
  password: {{ required "Please provide resticPassword" .Values.resticPassword | b64enc }}
---
