apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-app0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msg-label0
  template:
    metadata:
      labels:
        app: msg-label0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "3000"
    spec:
      containers: 
      - name: node-bgcolor
        image: dharapvj/bgcolor-text-demo:1.1
        ports:
        - containerPort: 3000
        env:
        - name: MESSAGE
          value: "Hello from the ArgoCD"
        - name: BGCOLOR
          value: "#348739"
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-svc
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: msg-label0
  type: LoadBalancer