name: "KKP Deploy Only"

on:
  workflow_call:
    # inputs:
    #   username:
    #     required: false
    #     type: string

# concurrancy is not supported for "called" workflows
#concurrency: ci-${{ github.ref }}

jobs:
  kkp-install:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Simple output
        working-directory: step2
        run: |
          cat step2.txt
