name: "Flux Deploy Only"

on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string

# concurrancy is not supported for "called" workflows
#concurrency: ci-${{ github.ref }}

jobs:
  helm-update:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Simple output
      uses: actions/hello-world-javascript-action@v1.1
      with:
        who-to-greet: ${{ inputs.username }}
