name: "Kubeone install Only"

on:
  push:
    branches:
      - main
    paths:
      - 'step1/**'
  pull_request:
    branches:
      - main
    paths:
      - 'step1/**'

concurrency: ci-${{ github.ref }}

jobs:
  kubeone-install:
    uses: dharapvj/workflow-testing/.github/workflows/reuse-kubeone-install.yaml@main
  kkp-install:
    uses: dharapvj/workflow-testing/.github/workflows/reuse-kkp-deploy.yaml@main
  call-flux-workflow:
    uses: dharapvj/workflow-testing/.github/workflows/reuse-flux-deploy.yaml@main
    with:
      username: vj
