name: "Flux Deploy Only"

on:
  push:
    branches:
      - main
    paths:
      - 'step3/**'
  pull_request:
    branches:
      - main
    paths:
      - 'step3/**'

concurrency: ci-${{ github.ref }}

jobs:
  call-flux-workflow:
    uses: dharapvj/workflow-testing/.github/workflows/reuse-flux-deploy.yaml@main
    with:
      username: vj
