name: "KKP Deploy Only"

on:
  push:
    branches:
      - main
    paths:
      - 'step2/**'
  pull_request:
    branches:
      - main
    paths:
      - 'step2/**'

concurrency: ci-${{ github.ref }}

jobs:
  kkp-install:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Simple output
        working-directory: step2
        run: |
          cat step2.txt
