name: "Kubeone install Only"

on:
  push:
    branches:
      - main
    paths:
      - 'step1/**'
  pull_request:
    branches:
      - main
    paths:
      - 'step1/**'

concurrency: ci-${{ github.ref }}

jobs:
  kubeone-install:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Simple output
        working-directory: step1
        run: |
          cat step1.txt
  call-kkp-install:
    uses: dharapvj/workflow-testing/.github/workflows/step2.yaml@main
    # with:
    #   username: vj
