name: "KKP Deploy Only"

on:
  push:
    branches:
      - main
    paths:
      - 'step2/**'
  pull_request:
    branches:
      - main
    paths:
      - 'step2/**'

concurrency: ci-${{ github.ref }}

jobs:
  kkp-install:
    uses: dharapvj/workflow-testing/.github/workflows/reuse-kkp-deploy.yaml@main
  call-flux-workflow:
    uses: dharapvj/workflow-testing/.github/workflows/reuse-flux-deploy.yaml@main
    with:
      username: vj
